// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Consent code generation module for wokelangiser — generates consent gate
// wrappers that enforce opt-in/opt-out behaviour around data collection points.
// Produces a consent state machine, per-category gates, and integration code.

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::abi::{ConsentCategory, ConsentGate, ConsentState};
use crate::codegen::parser::ConsentPoint;
use crate::manifest::Manifest;

// ---------------------------------------------------------------------------
// Consent gate generation
// ---------------------------------------------------------------------------

/// Generate consent gate code for all identified consent points.
/// Creates a consent manager module and individual gate wrappers.
///
/// Output structure:
///   {output_dir}/consent/
///     consent_manager.js   — State machine managing all consent categories
///     gates.js             — Individual consent gate wrapper functions
///     banner.html          — Consent banner template
pub fn generate_consent_gates(
    manifest: &Manifest,
    consent_points: &[ConsentPoint],
    output_dir: &str,
) -> Result<Vec<ConsentGate>> {
    let consent_dir = Path::new(output_dir).join("consent");
    fs::create_dir_all(&consent_dir)
        .with_context(|| format!("Failed to create consent output dir: {}", consent_dir.display()))?;

    // Build consent gates from the detected consent points.
    let default_state = parse_default_state(&manifest.consent.default_state);
    let mut gates: Vec<ConsentGate> = Vec::new();

    for (index, point) in consent_points.iter().enumerate() {
        let gate_id = format!(
            "{}_{}_{}",
            point.category.name(),
            sanitise_filename(&point.file),
            index
        );
        gates.push(ConsentGate {
            id: gate_id,
            category: point.category.clone(),
            state: default_state,
            description: point.description.clone(),
            gdpr_required: manifest.consent.gdpr,
            ccpa_required: manifest.consent.ccpa,
        });
    }

    // Also create gates for each configured category even if no points were found,
    // to ensure the consent banner covers all categories.
    for cat_name in &manifest.consent.categories {
        let category = ConsentCategory::from_str(cat_name);
        if !gates.iter().any(|g| g.category == category) {
            gates.push(ConsentGate {
                id: format!("{}_default", cat_name),
                category,
                state: default_state,
                description: format!("Default consent gate for {} category", cat_name),
                gdpr_required: manifest.consent.gdpr,
                ccpa_required: manifest.consent.ccpa,
            });
        }
    }

    // Generate the consent manager JavaScript module.
    let manager_code = generate_consent_manager(manifest, &gates);
    fs::write(consent_dir.join("consent_manager.js"), &manager_code)
        .context("Failed to write consent_manager.js")?;

    // Generate the individual gate wrapper functions.
    let gates_code = generate_gate_wrappers(&gates);
    fs::write(consent_dir.join("gates.js"), &gates_code)
        .context("Failed to write gates.js")?;

    // Generate the consent banner HTML template.
    let banner_html = generate_consent_banner(manifest, &gates);
    fs::write(consent_dir.join("banner.html"), &banner_html)
        .context("Failed to write banner.html")?;

    println!(
        "  Generated {} consent gates in {}",
        gates.len(),
        consent_dir.display()
    );

    Ok(gates)
}

/// Parse the default consent state from the manifest string value.
fn parse_default_state(state_str: &str) -> ConsentState {
    match state_str {
        "opt-in" => ConsentState::OptIn,
        "opt-out" => ConsentState::OptOut,
        _ => ConsentState::Pending,
    }
}

/// Generate the consent manager JavaScript module.
/// This implements a state machine that tracks consent for each category
/// and provides methods to grant, revoke, and query consent.
fn generate_consent_manager(manifest: &Manifest, gates: &[ConsentGate]) -> String {
    let categories: Vec<String> = manifest
        .consent
        .categories
        .iter()
        .map(|c| format!("\"{}\"", c))
        .collect();

    let default_state = if manifest.consent.default_state == "opt-in" {
        "\"opted_in\""
    } else {
        "\"opted_out\""
    };

    format!(
        r#"// SPDX-License-Identifier: PMPL-1.0-or-later
// Generated by wokelangiser — consent state machine
// Project: {project}
// GDPR: {gdpr} | CCPA: {ccpa}
// DO NOT EDIT — regenerate with `wokelangiser generate`

/**
 * ConsentManager — tracks user consent state for each data collection category.
 *
 * State transitions:
 *   pending  -> opted_in  (user grants consent)
 *   pending  -> opted_out (user denies consent or default applies)
 *   opted_in -> opted_out (user revokes consent)
 *   opted_out -> opted_in (user grants consent)
 *
 * Under GDPR (Article 7), consent must be freely given, specific, informed,
 * and unambiguous. Default state must be opted_out (no pre-ticked boxes).
 */
class ConsentManager {{
  constructor() {{
    this.categories = [{categories}];
    this.defaultState = {default_state};
    this.state = {{}};
    this.listeners = [];
    this._initialise();
  }}

  /** Initialise all categories to the default state. */
  _initialise() {{
    for (const category of this.categories) {{
      this.state[category] = this._loadState(category) || this.defaultState;
    }}
  }}

  /** Load persisted consent state from localStorage (if available). */
  _loadState(category) {{
    try {{
      return localStorage.getItem(`wokelangiser_consent_${{category}}`);
    }} catch (_) {{
      return null;
    }}
  }}

  /** Persist consent state to localStorage. */
  _saveState(category, state) {{
    try {{
      localStorage.setItem(`wokelangiser_consent_${{category}}`, state);
    }} catch (_) {{
      // localStorage unavailable — state is in-memory only.
    }}
  }}

  /** Grant consent for a category. */
  grant(category) {{
    if (!this.categories.includes(category)) return;
    this.state[category] = "opted_in";
    this._saveState(category, "opted_in");
    this._notify(category, "opted_in");
  }}

  /** Revoke consent for a category. */
  revoke(category) {{
    if (!this.categories.includes(category)) return;
    this.state[category] = "opted_out";
    this._saveState(category, "opted_out");
    this._notify(category, "opted_out");
  }}

  /** Grant consent for all categories. */
  grantAll() {{
    for (const category of this.categories) {{
      this.grant(category);
    }}
  }}

  /** Revoke consent for all categories. */
  revokeAll() {{
    for (const category of this.categories) {{
      this.revoke(category);
    }}
  }}

  /** Check if consent is granted for a category. */
  isAllowed(category) {{
    return this.state[category] === "opted_in";
  }}

  /** Register a listener for consent state changes. */
  onChange(listener) {{
    this.listeners.push(listener);
  }}

  /** Notify all listeners of a state change. */
  _notify(category, state) {{
    for (const listener of this.listeners) {{
      listener(category, state);
    }}
  }}

  /** Get the total number of gates managed. */
  get gateCount() {{
    return {gate_count};
  }}
}}

export const consentManager = new ConsentManager();
export default consentManager;
"#,
        project = manifest.project.name,
        gdpr = manifest.consent.gdpr,
        ccpa = manifest.consent.ccpa,
        categories = categories.join(", "),
        default_state = default_state,
        gate_count = gates.len(),
    )
}

/// Generate individual gate wrapper functions.
/// Each gate wraps a data collection call and only executes it if consent
/// has been granted for the associated category.
fn generate_gate_wrappers(gates: &[ConsentGate]) -> String {
    let mut code = String::from(
        "// SPDX-License-Identifier: PMPL-1.0-or-later\n\
         // Generated by wokelangiser — consent gate wrappers\n\
         // DO NOT EDIT — regenerate with `wokelangiser generate`\n\n\
         import { consentManager } from './consent_manager.js';\n\n",
    );

    for gate in gates {
        code.push_str(&format!(
            r#"/**
 * Consent gate: {id}
 * Category: {category}
 * Description: {description}
 * GDPR required: {gdpr} | CCPA required: {ccpa}
 *
 * Wraps a data collection function and only executes it if the user
 * has granted consent for the '{category}' category.
 *
 * @param {{Function}} collectionFn - The data collection function to gate.
 * @param {{...any}} args - Arguments to pass to the collection function.
 * @returns {{any|null}} The return value of collectionFn, or null if consent is not granted.
 */
export function gate_{safe_id}(collectionFn, ...args) {{
  if (!consentManager.isAllowed("{category}")) {{
    console.debug("[wokelangiser] Blocked: {id} (consent not granted for '{category}')");
    return null;
  }}
  return collectionFn(...args);
}}

"#,
            id = gate.id,
            safe_id = sanitise_identifier(&gate.id),
            category = gate.category.name(),
            description = gate.description,
            gdpr = gate.gdpr_required,
            ccpa = gate.ccpa_required,
        ));
    }

    code
}

/// Generate a consent banner HTML template.
/// The banner presents toggle switches for each consent category and
/// accept-all / reject-all buttons.
fn generate_consent_banner(manifest: &Manifest, _gates: &[ConsentGate]) -> String {
    let mut category_items = String::new();
    for cat in &manifest.consent.categories {
        category_items.push_str(&format!(
            r#"      <div class="wokelangiser-consent-item">
        <label for="consent-{cat}">
          <input type="checkbox" id="consent-{cat}" data-category="{cat}" />
          {cat_display}
        </label>
      </div>
"#,
            cat = cat,
            cat_display = capitalise(cat),
        ));
    }

    format!(
        r#"<!-- SPDX-License-Identifier: PMPL-1.0-or-later -->
<!-- Generated by wokelangiser — consent banner template -->
<!-- Project: {project} | GDPR: {gdpr} | CCPA: {ccpa} -->
<!-- DO NOT EDIT — regenerate with `wokelangiser generate` -->
<div id="wokelangiser-consent-banner" role="dialog" aria-label="Cookie consent preferences" aria-modal="true">
  <div class="wokelangiser-consent-content">
    <h2>Privacy Preferences</h2>
    <p>We use cookies and similar technologies to provide our services.
       Please choose which categories you consent to.</p>
    <div class="wokelangiser-consent-categories">
{categories}    </div>
    <div class="wokelangiser-consent-actions">
      <button id="wokelangiser-accept-all" aria-label="Accept all cookies">Accept All</button>
      <button id="wokelangiser-reject-all" aria-label="Reject all cookies">Reject All</button>
      <button id="wokelangiser-save-preferences" aria-label="Save cookie preferences">Save Preferences</button>
    </div>
  </div>
</div>
<script type="module">
  import {{ consentManager }} from './consent/consent_manager.js';

  document.getElementById('wokelangiser-accept-all').addEventListener('click', () => {{
    consentManager.grantAll();
    document.getElementById('wokelangiser-consent-banner').style.display = 'none';
  }});

  document.getElementById('wokelangiser-reject-all').addEventListener('click', () => {{
    consentManager.revokeAll();
    document.getElementById('wokelangiser-consent-banner').style.display = 'none';
  }});

  document.getElementById('wokelangiser-save-preferences').addEventListener('click', () => {{
    document.querySelectorAll('[data-category]').forEach(checkbox => {{
      const category = checkbox.dataset.category;
      if (checkbox.checked) {{
        consentManager.grant(category);
      }} else {{
        consentManager.revoke(category);
      }}
    }});
    document.getElementById('wokelangiser-consent-banner').style.display = 'none';
  }});
</script>
"#,
        project = manifest.project.name,
        gdpr = manifest.consent.gdpr,
        ccpa = manifest.consent.ccpa,
        categories = category_items,
    )
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Sanitise a file path into a safe identifier fragment.
fn sanitise_filename(path: &str) -> String {
    path.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

/// Sanitise a string into a valid JavaScript identifier.
fn sanitise_identifier(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

/// Capitalise the first letter of a string.
fn capitalise(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().to_string() + chars.as_str(),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_default_state() {
        assert_eq!(parse_default_state("opt-in"), ConsentState::OptIn);
        assert_eq!(parse_default_state("opt-out"), ConsentState::OptOut);
        assert_eq!(parse_default_state("unknown"), ConsentState::Pending);
    }

    #[test]
    fn test_sanitise_filename() {
        assert_eq!(sanitise_filename("src/app.js"), "src_app_js");
        assert_eq!(sanitise_filename("./index.html"), "index_html");
    }

    #[test]
    fn test_sanitise_identifier() {
        assert_eq!(sanitise_identifier("analytics_pageview_0"), "analytics_pageview_0");
        assert_eq!(sanitise_identifier("gate-name.test"), "gate_name_test");
    }

    #[test]
    fn test_capitalise() {
        assert_eq!(capitalise("analytics"), "Analytics");
        assert_eq!(capitalise(""), "");
    }

    #[test]
    fn test_generate_consent_manager_contains_categories() {
        let manifest = crate::manifest::Manifest {
            project: crate::manifest::ProjectConfig {
                name: "test".to_string(),
                source_root: ".".to_string(),
            },
            consent: crate::manifest::ConsentConfig {
                gdpr: true,
                ccpa: false,
                default_state: "opt-out".to_string(),
                categories: vec!["analytics".to_string(), "marketing".to_string()],
            },
            accessibility: Default::default(),
            i18n: crate::manifest::I18nConfig {
                default_locale: "en-GB".to_string(),
                supported_locales: vec!["en-GB".to_string()],
                extract_strings: true,
            },
            report: Default::default(),
        };
        let gates = vec![];
        let code = generate_consent_manager(&manifest, &gates);
        assert!(code.contains("\"analytics\""));
        assert!(code.contains("\"marketing\""));
        assert!(code.contains("\"opted_out\""));
        assert!(code.contains("class ConsentManager"));
    }
}
